### ISSUE TITLE
--api

### ISSUE THREAD

**Issue by yegor256** [yegor256/sibit#20]
Let's make it possible to specify a list of APIs to use, in any particular order, for example:

```
--api=blockchain.info,chain.so,block.io
```

They should be used in this particular order. If the first one fails, the second one is attempted, and so on.

**Comment by yegor256** [comment]
I asked for help here: https://twitter.com/yegor256/status/1131090804259414016

**Comment by yegor256** [comment]
http://api.blockcypher.com  is an option too.

**Comment by aivinog1** [comment]
@yegor256 I can start working with this issue using PDD (starting with small requests with todo). 

Is this okay?

BTW, I'm totally new in Ruby.

**Comment by yegor256** [comment]
@aivinog1 sure, go ahead and make a first pull request

**Comment by 0pdd** [comment]
@yegor256 2 puzzles [#35](https://github.com/yegor256/sibit/issues/35), [#36](https://github.com/yegor256/sibit/issues/36) are still not solved.

**Comment by 0crat** [comment]
Job `gh:yegor256/sibit#20` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by 0pdd** [comment]
@yegor256 2 puzzles [#36](https://github.com/yegor256/sibit/issues/36), [#40](https://github.com/yegor256/sibit/issues/40) are still not solved; solved: [#35](https://github.com/yegor256/sibit/issues/35).

**Comment by 0pdd** [comment]
@yegor256 all 3 puzzles are solved here: [#35](https://github.com/yegor256/sibit/issues/35), [#36](https://github.com/yegor256/sibit/issues/36), [#40](https://github.com/yegor256/sibit/issues/40).
