### ISSUE TITLE
Why the bin folder excluded from the rubocop?

### ISSUE THREAD

**Issue by aivinog1** [yegor256/sibit#30]
Now .rubocop.yml contains this (https://github.com/yegor256/sibit/blob/e8ad1155cb35e038cc5eb6a21564d758d9df7f7f/.rubocop.yml#L3):

Why needs to exclude the bin folder?

**Comment by yegor256** [comment]
@aivinog1 seems like a bug

**Comment by yegor256** [comment]
@aivinog1 I fixed it in 51e90b7 thanks!
