### ISSUE TITLE
Rultor merge isn't working

### ISSUE THREAD

**Issue by aivinog1** [yegor256/sibit#32]
See this: https://github.com/yegor256/sibit/pull/31#issuecomment-508638965

Seems like a `rultor merge` command isn't working.

**Comment by 0crat** [comment]
@aivinog1[/z](https://www.0crat.com/u/aivinog1) I'm not managing this repo, remove the [webhook](https://github.com/yegor256/sibit/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `yegor256/sibit` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@aivinog1 fixed in ad348f8 thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/sibit#32` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
