### ISSUE TITLE
sibit:59-60: For now this feature is not implemented....

### ISSUE THREAD

**Issue by 0pdd** [yegor256/sibit#36]
The puzzle `20-0615e900` from #20 has to be resolved: 

https://github.com/yegor256/sibit/blob/5046046b3044feb93ffef14ccddac36a9c0c766f/bin/sibit#L59-L60

The puzzle was created by Alexey Vinogradov on 09-Jul-19. 

Estimate: 60 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#36](https://github.com/yegor256/sibit/issues/36) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#36](https://github.com/yegor256/sibit/issues/36); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#36](https://github.com/yegor256/sibit/issues/36); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@0crat assign @aivinog1

**Comment by 0crat** [comment]
> @0crat assign @aivinog1  ([here](https://github.com/yegor256/sibit/issues/36#issuecomment-511229567))

@yegor256 The job [#36](https://github.com/yegor256/sibit/issues/36) assigned to @aivinog1[/z](https://www.0crat.com/u/aivinog1), here is [why](https://www.0crat.com/footprint/C3RFVLU72/4b575230-f492-4e1b-8b4a-fd48401216b8); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @aivinog1[/z](https://www.0crat.com/u/aivinog1) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by aivinog1** [comment]
@0crat wait #38.

**Comment by aivinog1** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat wait #38.  ([here](https://github.com/yegor256/sibit/issues/36#issuecomment-511761753))

@aivinog1 The impediment for [#36](https://github.com/yegor256/sibit/issues/36) was registered successfully by @aivinog1[/z](https://www.0crat.com/u/aivinog1)

**Comment by 0crat** [comment]
> @0crat wait #38.  ([here](https://github.com/yegor256/sibit/issues/36#issuecomment-511761753))

@aivinog1 There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@e9bedd73-1aea-4276-9609-4daad31b221f, thread: pool-18-thread-7
org.codehaus.groovy.runtime.ScriptBytecodeAdapter[66] groovy.lang.MissingPropertyException: No such property: issue for class: com.zerocracy.stk.pm.in.impediments.add_waiting_label
```

[0.48.2](https://github.com/zerocracy/farm): CID: [14a28df5-f7f2-476b-b699-977473f8fb04](https://www.0crat.com/footprint/C3RFVLU72/14a28df5-f7f2-476b-b699-977473f8fb04), Type: "Impediment was registered"

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/sibit/issues/36#issuecomment-511764273))

@aivinog1 This is what I know about this job in [C3RFVLU72](https://www.0crat.com/p/C3RFVLU72), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#36](https://github.com/yegor256/sibit/issues/36) is [in scope](http://www.zerocracy.com/policy.html#14) for 7days
  * The role is `DEV`
  * The job is assigned to @aivinog1[/z](https://www.0crat.com/u/aivinog1) for [2days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job has an [impediment](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3RFVLU72?q=%7Bjob%3A%27gh%3Ayegor256%2Fsibit%2336%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by aivinog1** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/sibit/issues/36#issuecomment-513605353))

@aivinog1 This is what I know about this job in [C3RFVLU72](https://www.0crat.com/p/C3RFVLU72), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#36](https://github.com/yegor256/sibit/issues/36) is [in scope](http://www.zerocracy.com/policy.html#14) for 13days
  * The role is `DEV`
  * The job is assigned to @aivinog1[/z](https://www.0crat.com/u/aivinog1) for [7days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job has an [impediment](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3RFVLU72?q=%7Bjob%3A%27gh%3Ayegor256%2Fsibit%2336%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0pdd** [comment]
The puzzle `20-0615e900` has disappeared from the source code, that's why I closed this issue.

**Comment by yegor256** [comment]
@rultor release, tag is `0.12.6`

**Comment by 0crat** [comment]
Job [#36](https://github.com/yegor256/sibit/issues/36) is closed, can't start order

**Comment by 0crat** [comment]
Job [#36](https://github.com/yegor256/sibit/issues/36) is not in the agenda of @aivinog1[/z](https://www.0crat.com/u/aivinog1), can't retrieve data and time of add

**Comment by 0crat** [comment]
The job [#36](https://github.com/yegor256/sibit/issues/36) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @aivinog1[/z](https://www.0crat.com/u/aivinog1)
