### ISSUE TITLE
Let's verify PDD TODO's in the .travis.yml

### ISSUE THREAD

**Issue by aivinog1** [yegor256/sibit#39]
For now, todos verified only in https://github.com/yegor256/sibit/blob/5046046b3044feb93ffef14ccddac36a9c0c766f/.rultor.yml#L22

Let's add this check in the `.travis.yml` file.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@aivinog1[/z](https://www.0crat.com/u/aivinog1) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RFVLU72) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@aivinog1 fixed, thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/sibit#39` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
